### ISSUE TITLE
好兄弟，我也是理工大的，你哪个院的

### ISSUE THREAD

**Issue by cyberayu** [zhjue/hpu-lib-api#2]
最近我也在做一个占座器，没想到遇到前辈了🤣

**Comment by zhang-weiyu** [comment]
> 最近我也在做一个占座器，没想到遇到前辈了🤣

我能源的

**Comment by cyberayu** [comment]
> > 最近我也在做一个占座器，没想到遇到前辈了🤣
> 
> 
> 
> 我能源的
厉害了，洒家物电的。没想到还能遇到熟人

**Comment by zhang-weiyu** [comment]
@apendly 
hhh
